output: mcs.e mono.e clean
 
mcs.e:
	mcs Program.cs View/Cadastro/CadastraCliente.cs View/Cadastro/CadastraLocacao.cs View/Cadastro/CadastraVeiculoLeve.cs View/Cadastro/CadastraVeiculoPesado.cs View/Edicao/EditaCliente.cs View/Edicao/EditaLocacao.cs View/Edicao/EditaVeiculoLeve.cs View/Edicao/EditaVeiculoPesado.cs View/Atualizacao/AtualizaCliente.cs View/Atualizacao/AtualizaLocacao.cs View/Atualizacao/AtualizaVeiculoLeve.cs View/Atualizacao/AtualizaVeiculoPesado.cs View/Exclusao/ExcluiCliente.cs View/Exclusao/ExcluiLocacao.cs View/Exclusao/ExcluiVeiculoLeve.cs View/Exclusao/ExcluiVeiculoPesado.cs View/Biblio/* -r:System.Windows.Forms.dll,System.Drawing.dll 
mono.e:
	mono Program.exe
 
clean:
	rm *.exe 